adding pod scalling job

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -82,3 +82,68 @@ jobs:
             --nodes-max=${{ vars.NODEGROUP_MAX_SIZE }} \
             --nodes=${{ vars.NODEGROUP_DESIRED_SIZE }} \
             --region=us-east-1
+
+  scale-pods:
+    if: vars.INFRA_ALREADY_CREATED == 'true'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Configure AWS credentials (OIDC)
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/AWSRoleForGithubActions
+          aws-region: us-east-1
+
+      - name: Install kubectl
+        run: |
+          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
+          chmod +x ./kubectl
+          sudo mv ./kubectl /usr/local/bin/kubectl
+
+      - name: Set up KUBECONFIG for EKS
+        run: |
+          aws eks update-kubeconfig \
+            --name ${{ vars.CLUSTER_NAME }} \
+            --region us-east-1
+
+      - name: Validate replica values
+        run: |
+          REPLICAS=${{ vars.POD_DESIRED_REPLICAS }}
+          MIN=${{ vars.POD_MIN_REPLICAS }}
+          MAX=${{ vars.POD_MAX_REPLICAS }}
+
+          echo "Min=$MIN | Max=$MAX | Desired=$REPLICAS"
+
+          if [ "$REPLICAS" -lt "$MIN" ] || [ "$REPLICAS" -gt "$MAX" ]; then
+            echo "ERROR: DESIRED ($REPLICAS) must be between MIN ($MIN) and MAX ($MAX)"
+            exit 1
+          fi
+
+      - name: Scale pod replicas
+        run: |
+          kubectl scale deployment ${{ vars.DEPLOYMENT_NAME }} \
+            --replicas=${{ vars.POD_DESIRED_REPLICAS }} \
+            --namespace=${{ vars.NAMESPACE }}
+
+      - name: Verify
+        run: |
+          echo "=== Deployment ==="
+          kubectl get deployment ${{ vars.DEPLOYMENT_NAME }} -n ${{ vars.NAMESPACE }}
+
+
+# ### Add these GitHub Variables
+# ```
+# POD_DESIRED_REPLICAS  = 2
+# POD_MIN_REPLICAS      = 1
+# POD_MAX_REPLICAS      = 2
+# DEPLOYMENT_NAME       = my-app
+# HPA_NAME              = my-app-hpa
+# NAMESPACE             = staging
+# ```
+
+# ---
+
+# ### Full picture of all 3 jobs now
+# ```
+# INFRA_ALREADY_CREATED = false  →  terraform job runs        (creates infra)
+# INFRA_ALREADY_CREATED = true   →  scale-nodegroup job runs  (scales nodes)
+#                                    scale-pods job runs       (scales pods)
